/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import init.Main;
import init.WindowManager;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Shai Gutman
 */
public class createShow extends javax.swing.JPanel {

    /**
     * Creates new form createShow
     */
    public createShow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Set ticket price:");
        add(jLabel6);
        jLabel6.setBounds(60, 190, 140, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Set minimum age:");
        add(jLabel7);
        jLabel7.setBounds(60, 160, 140, 20);

        jTextField3.setPreferredSize(new java.awt.Dimension(30, 25));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3);
        jTextField3.setBounds(250, 190, 140, 25);

        jTextField1.setPreferredSize(new java.awt.Dimension(30, 25));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(250, 160, 140, 25);

        jComboBox2.addItem("Select Place");
        add(jComboBox2);
        jComboBox2.setBounds(250, 130, 140, 25);

        jComboBox1.addItem("Select Artist");
        add(jComboBox1);
        jComboBox1.setBounds(250, 100, 140, 25);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Available Places for date:");
        add(jLabel5);
        jLabel5.setBounds(60, 130, 180, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Available Artists for date:");
        add(jLabel4);
        jLabel4.setBounds(60, 100, 180, 20);

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });
        add(jXDatePicker1);
        jXDatePicker1.setBounds(250, 70, 140, 24);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Create New Show");
        add(jLabel3);
        jLabel3.setBounds(60, 20, 230, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose show's date:");
        add(jLabel2);
        jLabel2.setBounds(60, 70, 150, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container1.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        jXDatePicker1.setEditable(false);
        Date selectedDate = new Date(jXDatePicker1.getDate().getDay(), jXDatePicker1.getDate().getMonth(), jXDatePicker1.getDate().getYear());
        ResultSet rs1 = Main.getDB().query("SELECT tblArtist.*\n" +
                                            "FROM tblAgent INNER JOIN tblArtist ON tblAgent.ID = tblArtist.agentID\n" +
                                            "WHERE (((tblArtist.agentID)=\""+WindowManager.getTmpAgent().getId()+"\"))");
        ResultSet rs2 = Main.getDB().query("SELECT tblPerformance.artistID\n" +
                                            "FROM tblShow INNER JOIN tblPerformance ON tblShow.ID = tblPerformance.showID\n" +
                                            "WHERE (((tblPerformance.showID)=[tblShow].[ID]) AND ((tblShow.date)=#"+selectedDate+"#))");  
        ResultSet rs3 = Main.getDB().query("SELECT tblPlace.*, tblFavoritePlace.agentID\n" +
                                            "FROM tblPlace INNER JOIN tblFavoritePlace ON tblPlace.ID = tblFavoritePlace.placeID\n" +
                                            "WHERE (((tblFavoritePlace.agentID)=\""+WindowManager.getTmpAgent().getId()+"\"))");      
        ResultSet rs4 = Main.getDB().query("SELECT tblPlace.*, tblShow.date, tblShow.place\n" +
                                            "FROM tblPlace INNER JOIN tblShow ON tblPlace.ID = tblShow.place\n" +
                                            "WHERE (((tblShow.date)=#"+selectedDate+"#) AND ((tblShow.place)=[tblPlace].[ID]))");  
        HashMap<String,String> availableAgents = new HashMap<>();
        HashMap<String,String> availableShows = new HashMap<>();
        try {
            while (rs1.next()) {
                availableAgents.put(rs1.getString(1), rs1.getString(2));
            }
            while (rs2.next()) {
                if (availableAgents.containsKey(rs2.getString(1))) {
                    availableAgents.remove(rs2.getString(1));
                }
            }
            for (String s : availableAgents.keySet()) {
                jComboBox1.addItem(s);
            }
        } catch (SQLException ex) {
            Logger.getLogger(createShow.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            while (rs3.next()) {
                availableShows.put(rs3.getString(1), rs3.getString(2));
            }
            while (rs4.next()) {
                if (availableShows.containsKey(rs4.getString(1))) {
                    availableShows.remove(rs4.getString(1));
                }
            }
            for (String s : availableShows.keySet()) {
                jComboBox2.addItem(s);
            }
        } catch (SQLException ex) {
            Logger.getLogger(createShow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
