/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import core.Agent;
import init.MainClass;

import init.WindowManager;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shai Gutman
 */
public class MainLogin extends javax.swing.JFrame {

    /**
     * Creates new form MainLogin
     */
    public MainLogin() throws SQLException {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitBtn = new javax.swing.JButton();
        forgotPasswordBtn2 = new javax.swing.JButton();
        newAccountBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/exitBtn.png"))); // NOI18N
        exitBtn.setBorder(null);
        exitBtn.setBorderPainted(false);
        exitBtn.setContentAreaFilled(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn);
        exitBtn.setBounds(1070, 610, 130, 40);

        forgotPasswordBtn2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        forgotPasswordBtn2.setForeground(new java.awt.Color(0, 0, 0));
        forgotPasswordBtn2.setText("Forgot password");
        forgotPasswordBtn2.setBorder(null);
        forgotPasswordBtn2.setBorderPainted(false);
        forgotPasswordBtn2.setContentAreaFilled(false);
        forgotPasswordBtn2.setDefaultCapable(false);
        forgotPasswordBtn2.setFocusPainted(false);
        forgotPasswordBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(forgotPasswordBtn2);
        forgotPasswordBtn2.setBounds(880, 500, 140, 20);

        newAccountBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        newAccountBtn.setForeground(new java.awt.Color(0, 0, 0));
        newAccountBtn.setText("Create new account");
        newAccountBtn.setBorder(null);
        newAccountBtn.setBorderPainted(false);
        newAccountBtn.setContentAreaFilled(false);
        newAccountBtn.setDefaultCapable(false);
        newAccountBtn.setFocusPainted(false);
        newAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newAccountBtn);
        newAccountBtn.setBounds(710, 500, 160, 20);

        loginBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setBorder(null);
        loginBtn.setBorderPainted(false);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setDefaultCapable(false);
        loginBtn.setFocusPainted(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(713, 440, 310, 40);

        passwordField.setBorder(null);
        passwordField.setOpaque(false);
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(passwordField);
        passwordField.setBounds(740, 390, 280, 30);

        usernameField.setBorder(null);
        usernameField.setOpaque(false);
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldKeyPressed(evt);
            }
        });
        getContentPane().add(usernameField);
        usernameField.setBounds(740, 340, 280, 30);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/muzaLogin.png"))); // NOI18N
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 1200, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(1);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void newAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newAccountBtnActionPerformed

    private void forgotPasswordBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotPasswordBtn2ActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

    }//GEN-LAST:event_loginBtnActionPerformed

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            openMain();
        }
    }//GEN-LAST:event_usernameFieldKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            openMain();
        }
    }//GEN-LAST:event_passwordFieldKeyPressed
    public void openMain() {
        if (usernameField.getText().equals("") || passwordField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "You must enter username & password", "Login error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (usernameField.getText().equals("Admin") || passwordField.getText().equals("Admin")) {
            WindowManager.startMain();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton forgotPasswordBtn2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton newAccountBtn;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
