/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import init.WindowManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Shai Gutman
 */
public class MainGui extends JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        reportProduceBtn = new javax.swing.JButton();
        parametersBtn = new javax.swing.JButton();
        createAgentBtn = new javax.swing.JButton();
        viewAgentBtn = new javax.swing.JButton();
        agentBtn = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/arrowBtn.png"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(190, 610, 80, 65);

        if (WindowManager.getAuthValue() == 1)
        adminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/agentBtn.png"))); // NOI18N
        if (WindowManager.getAuthValue() == 0)
        adminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/repBtn.png"))); // NOI18N
        adminBtn.setBorder(null);
        adminBtn.setBorderPainted(false);
        adminBtn.setContentAreaFilled(false);
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adminBtn);
        adminBtn.setBounds(1070, 520, 130, 40);

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logoutBtn.png"))); // NOI18N
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn);
        logoutBtn.setBounds(1070, 565, 130, 40);

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/exitBtn.png"))); // NOI18N
        exitBtn.setBorder(null);
        exitBtn.setBorderPainted(false);
        exitBtn.setContentAreaFilled(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn);
        exitBtn.setBounds(1070, 610, 130, 40);

        reportProduceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn3.png"))); // NOI18N
        reportProduceBtn.setBorderPainted(false);
        reportProduceBtn.setContentAreaFilled(false);
        reportProduceBtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn3dis.png"))); // NOI18N
        reportProduceBtn.setDisabledSelectedIcon(null);
        reportProduceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportProduceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(reportProduceBtn);
        reportProduceBtn.setBounds(35, 410, 225, 50);

        parametersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/paramBtn1.png"))); // NOI18N
        parametersBtn.setBorderPainted(false);
        parametersBtn.setContentAreaFilled(false);
        parametersBtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn3dis.png"))); // NOI18N
        parametersBtn.setDisabledSelectedIcon(null);
        parametersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametersBtnActionPerformed(evt);
            }
        });
        getContentPane().add(parametersBtn);
        parametersBtn.setBounds(35, 365, 225, 50);

        createAgentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/createAgentBtn2.png"))); // NOI18N
        createAgentBtn.setBorderPainted(false);
        createAgentBtn.setContentAreaFilled(false);
        createAgentBtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn1dis.png"))); // NOI18N
        createAgentBtn.setDisabledSelectedIcon(null);
        createAgentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAgentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createAgentBtn);
        createAgentBtn.setBounds(57, 305, 180, 31);

        viewAgentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/viewAgentBtn2.png"))); // NOI18N
        viewAgentBtn.setBorderPainted(false);
        viewAgentBtn.setContentAreaFilled(false);
        viewAgentBtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btn1dis.png"))); // NOI18N
        viewAgentBtn.setDisabledSelectedIcon(null);
        viewAgentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAgentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewAgentBtn);
        viewAgentBtn.setBounds(57, 336, 180, 31);

        agentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/agentBtn1.png"))); // NOI18N
        agentBtn.setBorderPainted(false);
        agentBtn.setContentAreaFilled(false);
        agentBtn.setDisabledIcon(null);
        agentBtn.setDisabledSelectedIcon(null);
        agentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(agentBtn);
        agentBtn.setBounds(35, 260, 225, 50);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/MuzaBack.png"))); // NOI18N
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 1200, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentBtnActionPerformed
        
    }//GEN-LAST:event_agentBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(1);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        try {
            WindowManager.closeMain();
        } catch (SQLException ex) {
            Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        WindowManager.returnWindow();
    }//GEN-LAST:event_backBtnActionPerformed

    private void parametersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametersBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parametersBtnActionPerformed

    private void viewAgentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAgentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewAgentBtnActionPerformed

    private void createAgentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAgentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createAgentBtnActionPerformed

    private void reportProduceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportProduceBtnActionPerformed
        WindowManager.openWin(new ReportProduce());
    }//GEN-LAST:event_reportProduceBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton agentBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createAgentBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton parametersBtn;
    private javax.swing.JButton reportProduceBtn;
    private javax.swing.JButton viewAgentBtn;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
