/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import businessLogic.ChangeArtistDetailsControl;
import businessLogic.ReportProduceControl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author Shai Gutman
 */
public class ChangeArtistDetails extends javax.swing.JPanel {

    ReportProduceControl rpController = new ReportProduceControl();
    
    public ChangeArtistDetails() {
        initComponents();
        rs = con.getArtistsPerAgent();
        if (rs!=null){
            try {
                while (rs.next())
                    jComboBox1.addItem(rs.getString(2));
                //  jComboBox1.setSelectedIndex(0);
            } catch (SQLException ex) {
                Logger.getLogger(ViewAgents.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable() {
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return Boolean.class;
                    case 1:
                    return String.class;
                    case 2:
                    return String.class;
                    case 3:
                    return String.class;
                    case 4:
                    return String.class;
                    case 5:
                    return String.class;
                    default:
                    return Boolean.class;
                }
            }
        }
        ;
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Change Artist Details :");
        add(jLabel4);
        jLabel4.setBounds(30, 10, 250, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Artist Name :");
        add(jLabel2);
        jLabel2.setBounds(30, 70, 90, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("FaceBook :");
        add(jLabel5);
        jLabel5.setBounds(30, 110, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email :");
        add(jLabel6);
        jLabel6.setBounds(30, 150, 110, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Biography :");
        add(jLabel11);
        jLabel11.setBounds(340, 70, 110, 15);
        add(jTextField4);
        jTextField4.setBounds(140, 100, 150, 30);
        add(jTextField9);
        jTextField9.setBounds(430, 60, 350, 150);
        add(jTextField5);
        jTextField5.setBounds(140, 140, 150, 30);

        jButton1.setText("Save details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(580, 250, 180, 40);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(140, 60, 150, 30);
        add(jTextField6);
        jTextField6.setBounds(140, 180, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Appreciate :");
        add(jLabel7);
        jLabel7.setBounds(30, 280, 110, 15);

        jLabel3.setText("* Fill date the artist will be active again.  If you want the artist to be active now - leave the field empty    ");
        add(jLabel3);
        jLabel3.setBounds(30, 210, 580, 40);

        jTable1.setModel(new DefaultTableModel());
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 320, 720, 170);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Activation Date :");
        add(jLabel8);
        jLabel8.setBounds(30, 190, 110, 15);

        jButton2.setText("Set appreciate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(200, 510, 150, 50);

        jButton3.setText("Delete appreciate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(400, 510, 150, 50);

        jLabel9.setText("* Choose row and push the button you want");
        add(jLabel9);
        jLabel9.setBounds(30, 300, 300, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        /*List<String> artistsToApp = new ArrayList<String>();
        
        for (int i=0;i<jTable1.getModel().getRowCount();i++){
            if ((boolean)jTable1.getModel().getValueAt(i, 0))
                artistsToApp.add((String)jTable1.getModel().getValueAt(i, 1));
        }*/
        
        con.updateDetails(artistIdSelected, jTextField4.getText(), jTextField5.getText(), jTextField6.getText(), jTextField9.getText());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        rs = con.getArtistsPerAgent();
        int count = jComboBox1.getSelectedIndex()+1;
        int counter = 1;
        try {
            while (rs.next()){
                if (counter == count){
                    artistIdSelected = rs.getString(1);
                    // JOptionPane.showMessageDialog(null, artistIdSelected);
                    jTextField9.setText(rs.getString(3));
                    jTextField5.setText(rs.getString(4));
                    jTextField4.setText(rs.getString(5));
                    jTextField6.setText(rs.getString(9));
                    setTable(rs.getString(2));
                    break;
                }
                else counter++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewAgents.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTable1.getSelectedRow()<0) return;

        boolean flg = con.newApp(artistIdSelected, (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1),
                (boolean) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0));
        
        if (flg)
            jComboBox1ActionPerformed(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        boolean flg = con.deleteApp(artistIdSelected, (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1),
                (boolean) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0));
        
        if (flg)
            jComboBox1ActionPerformed(null);
    }//GEN-LAST:event_jButton3ActionPerformed
          
     public void setTable(String artistId){
        try {

        DefaultTableModel model = new DefaultTableModel(){

            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        
        jTable1.setModel(model);
        model.addColumn("Appreciate"); 
        model.addColumn("Stage Name");
        model.addColumn("Email"); 
        model.addColumn("Facebook"); 
        model.addColumn("isActive"); 
        model.addColumn("Activation Date");
        TableColumn tc = jTable1.getColumnModel().getColumn(0);
        tc.setCellEditor(jTable1.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(jTable1.getDefaultRenderer(Boolean.class));

        ResultSet artists = null;
            
        artists = con.getAllArtists();

            while(artists.next()){
                if (artistId.equals(artists.getString(2))) continue;
                
                ResultSet ra = con.checkAppreciate(artistIdSelected, artists.getString(1));
                        
                if (ra!=null && ra.next()){
                 model.addRow(new Object[]{true,artists.getString(2),artists.getString(3),artists.getString(4)
                 ,artists.getString(5),artists.getString(6)});
                }
                
                else{
                 model.addRow(new Object[]{false,artists.getString(2),artists.getString(3),artists.getString(4)
                 ,artists.getString(5),artists.getString(6)});
                }
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewAgents.class.getName()).log(Level.SEVERE, null, ex);
        }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    private ChangeArtistDetailsControl con = new ChangeArtistDetailsControl();
    private ResultSet rs = null;
    private String artistIdSelected =  null;
}
