/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import businessLogic.CreateArtistControl;
import businessLogic.HandsInTheAir;
import businessLogic.ReportProduceControl;
import businessLogic.ValidatorManager;
import businessLogic.WindowManager;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author Shai Gutman
 */
public class CreateArtist extends javax.swing.JPanel {

    ReportProduceControl rpController = new ReportProduceControl();
    
    public CreateArtist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        uploadButton = new javax.swing.JButton();
        profileLabel = new javax.swing.JLabel();
        profileField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Create Artist ");
        add(jLabel4);
        jLabel4.setBounds(30, 10, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Stage Name :");
        add(jLabel3);
        jLabel3.setBounds(30, 70, 90, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("FaceBook :");
        add(jLabel5);
        jLabel5.setBounds(30, 110, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Choose signature picture :");
        add(jLabel6);
        jLabel6.setBounds(30, 200, 200, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Biography :");
        add(jLabel11);
        jLabel11.setBounds(350, 70, 110, 15);
        add(jTextField2);
        jTextField2.setBounds(170, 60, 150, 30);
        add(jTextField4);
        jTextField4.setBounds(170, 100, 150, 30);
        add(jTextField9);
        jTextField9.setBounds(440, 60, 340, 70);
        add(jTextField5);
        jTextField5.setBounds(170, 140, 150, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(620, 420, 90, 40);

        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });
        add(uploadButton);
        uploadButton.setBounds(30, 260, 80, 20);

        profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/defaultProfile.png"))); // NOI18N
        add(profileLabel);
        profileLabel.setBounds(260, 190, 140, 150);

        profileField.setEditable(false);
        add(profileField);
        profileField.setBounds(30, 230, 200, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Email :");
        add(jLabel7);
        jLabel7.setBounds(30, 150, 110, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DataSource source = new FileDataSource(profileField.getText());
       /* MimeBodyPart messageBodyPart = new MimeBodyPart();     
        try {
            messageBodyPart.setFileName(profileField.getText());
        } catch (MessagingException ex) {
            Logger.getLogger(CreateArtist.class.getName()).log(Level.SEVERE, null, ex);
        }
        messageBodyPart.setDataHandler(new DataHandler(source));*/
        
       con.newArtist(jTextField2.getText(),jTextField9.getText(),jTextField5.getText(),jTextField4.getText(),true,source, WindowManager.getTmpAgent().getId());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File chosen = chooser.getSelectedFile();
        String filename = chosen.getAbsolutePath();
        profileField.setText(filename);
        profileLabel.setIcon(new ImageIcon(filename));
    }//GEN-LAST:event_uploadButtonActionPerformed
        
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField profileField;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
    private CreateArtistControl con = new CreateArtistControl();
}
