/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import businessLogic.CreatePlaceControl;
import businessLogic.ReportProduceControl;
import entity.E_CITIES;

/**
 *
 * @author Shai Gutman
 */
public class CreatePlace extends javax.swing.JPanel {

    ReportProduceControl rpController = new ReportProduceControl();
    
    public CreatePlace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Create Place ");
        add(jLabel4);
        jLabel4.setBounds(30, 10, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Place Name :");
        add(jLabel3);
        jLabel3.setBounds(30, 70, 90, 15);
        add(jTextField2);
        jTextField2.setBounds(130, 60, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("City :");
        add(jLabel5);
        jLabel5.setBounds(30, 110, 90, 15);
        add(jTextField4);
        jTextField4.setBounds(130, 140, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Street :");
        add(jLabel6);
        jLabel6.setBounds(30, 150, 110, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("House Number :");
        add(jLabel7);
        jLabel7.setBounds(30, 190, 100, 15);
        add(jTextField5);
        jTextField5.setBounds(130, 180, 150, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(580, 500, 160, 40);
        add(jTextField7);
        jTextField7.setBounds(440, 140, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Location :");
        add(jLabel9);
        jLabel9.setBounds(340, 150, 100, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Phone Number :");
        add(jLabel10);
        jLabel10.setBounds(340, 110, 100, 15);
        add(jTextField8);
        jTextField8.setBounds(440, 100, 150, 30);
        add(jTextField9);
        jTextField9.setBounds(440, 60, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Email :");
        add(jLabel11);
        jLabel11.setBounds(340, 70, 110, 15);
        add(jTextField10);
        jTextField10.setBounds(440, 180, 150, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Max Capacity :");
        add(jLabel12);
        jLabel12.setBounds(340, 190, 100, 15);

        add(jComboBox2);
        jComboBox2.setBounds(130, 100, 150, 30);
        jComboBox2.removeAllItems();
        for (E_CITIES e : con.ListOfCity("Israel"))
        jComboBox2.addItem(e.toString());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Toilets :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 180, 90, 15);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Partial", "Full" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(110, 10, 150, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Cover :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 20, 90, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Seats :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 60, 90, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Platform:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 100, 90, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Gear :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 140, 90, 15);
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(110, 50, 20, 21);
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(110, 90, 21, 21);
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(110, 130, 21, 21);
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(110, 170, 21, 21);

        add(jPanel1);
        jPanel1.setBounds(30, 270, 690, 220);
        jPanel1.setVisible(false);

        jCheckBox1.setText("Check if you an open place");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1);
        jCheckBox1.setBounds(30, 230, 190, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        con.newPlace(jTextField2.getText(), jTextField4.getText(), jTextField5.getText(), jComboBox2.getSelectedItem().toString(), jTextField9.getText(), jTextField8.getText(), jTextField7.getText(), jTextField10.getText(),
                jCheckBox1.isSelected(),jComboBox3.getSelectedItem().toString(),jCheckBox2.isSelected(),jCheckBox3.isSelected(),jCheckBox4.isSelected(),jCheckBox5.isSelected());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected())
            jPanel1.setVisible(true);
        else 
            jPanel1.setVisible(false);   
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    private CreatePlaceControl con = new CreatePlaceControl();
}
