/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import entity.Address;
import entity.Agent;
import entity.Artist;
import entity.Place;
import businessLogic.CreateShowControl;
import businessLogic.DBManager;
import businessLogic.HandsInTheAir;
import businessLogic.WindowManager;
import java.awt.Checkbox;
import java.awt.Component;
import java.awt.Font;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.font.TextAttribute;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JViewport;
import javax.swing.SpinnerDateModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicComboBoxRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.ucanaccess.converters.Functions;

/**
 *
 * @author Shai Gutman
 */
public class CreateShow extends javax.swing.JPanel {
    CreateShowControl csController = new CreateShowControl();
    HashMap<String, String> artistIDOf;
    /**
     * Creates new form createShow
     */
    public CreateShow() {
        artistIDOf = new HashMap<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable() {
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    case 2:
                    return Integer.class;
                    case 3:
                    return Double.class;
                    default:
                    return Boolean.class;
                }
            }
        };
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        startTextField = new javax.swing.JTextField();
        ticketTextField = new javax.swing.JTextField();
        minageTextField = new javax.swing.JTextField();
        placeComboBox = new javax.swing.JComboBox<>();
        artistComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);
        jPanel1.setVisible(false);

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Biography:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(380, 120, 330, 20);

        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 10, 340, 230);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Selected artist info:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(380, 30, 190, 20);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Facebook:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(380, 100, 330, 20);

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Agent:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(380, 60, 330, 20);

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Email:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(380, 80, 330, 20);

        add(jPanel1);
        jPanel1.setBounds(25, 315, 730, 250);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Address:");
        add(jLabel15);
        jLabel15.setBounds(420, 150, 400, 20);

        jButton3.setText("Create Show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(230, 270, 130, 26);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Choose show's start time:");
        add(jLabel17);
        jLabel17.setBounds(50, 100, 180, 20);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Phone number:");
        add(jLabel14);
        jLabel14.setBounds(420, 130, 400, 20);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Maximum capacity:");
        add(jLabel11);
        jLabel11.setBounds(420, 190, 400, 20);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Loacation:");
        add(jLabel12);
        jLabel12.setBounds(420, 170, 400, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Email:");
        add(jLabel10);
        jLabel10.setBounds(420, 110, 400, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Name:");
        add(jLabel9);
        jLabel9.setBounds(420, 90, 400, 20);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Selected place info:");
        add(jLabel8);
        jLabel8.setBounds(420, 70, 170, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Set ticket price:");
        add(jLabel6);
        jLabel6.setBounds(50, 190, 140, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Set minimum age:");
        add(jLabel7);
        jLabel7.setBounds(50, 220, 140, 20);

        startTextField.setPreferredSize(new java.awt.Dimension(30, 25));
        startTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTextFieldActionPerformed(evt);
            }
        });
        add(startTextField);
        startTextField.setBounds(240, 100, 140, 25);

        ticketTextField.setPreferredSize(new java.awt.Dimension(30, 25));
        ticketTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketTextFieldActionPerformed(evt);
            }
        });
        add(ticketTextField);
        ticketTextField.setBounds(240, 190, 140, 25);

        minageTextField.setPreferredSize(new java.awt.Dimension(30, 25));
        minageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minageTextFieldActionPerformed(evt);
            }
        });
        add(minageTextField);
        minageTextField.setBounds(240, 220, 140, 25);

        placeComboBox.setModel(new DefaultComboBoxModel<String>());
        placeComboBox.addItem("Select Place");
        placeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                placeComboBoxItemStateChanged(evt);
            }
        });
        add(placeComboBox);
        placeComboBox.setBounds(240, 160, 140, 25);

        artistComboBox.addItem("Select Artist");
        artistComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                artistComboBoxItemStateChanged(evt);
            }
        });
        add(artistComboBox);
        artistComboBox.setBounds(240, 130, 140, 25);

        jButton2.setText("Invite Artists");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(80, 270, 130, 26);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Available Places for date:");
        add(jLabel5);
        jLabel5.setBounds(50, 160, 180, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Available Artists for date:");
        add(jLabel4);
        jLabel4.setBounds(50, 130, 180, 20);

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });
        add(jXDatePicker1);
        jXDatePicker1.setBounds(240, 70, 110, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Choose show's date:");
        add(jLabel2);
        jLabel2.setBounds(50, 70, 150, 20);

        titleLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Create Show");
        add(titleLabel);
        titleLabel.setBounds(0, 10, 850, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        jXDatePicker1.setEditable(false);
        Date selectedDate = new Date(jXDatePicker1.getDate().getTime()); 
        boolean flag = false;
        for (Iterator<Artist> it = csController.getAvailableMainArtistForDate(selectedDate).iterator(); it.hasNext();) {
            Artist s = it.next();
            for (Map.Entry<String, ArrayList<java.util.Date>> entry : HandsInTheAir.getXML().getOccupied().entrySet()) {
                String key = entry.getKey();
                ArrayList<java.util.Date> value = entry.getValue();
                if (key.equals(s.getArtistAlphaCode()) && value.contains(selectedDate)) {
                    flag = true;
                }
            }
            if (flag)
                continue;
            artistComboBox.addItem(s.getStageName());
            artistIDOf.put(s.getStageName(), s.getArtistAlphaCode());
        }
        for (String s : csController.getAvailablePlacesForDate(selectedDate)) {
            placeComboBox.addItem(s);
        }
        placeComboBox.addItem("---------------------");
        for (String s : csController.getPlacesExcluding(selectedDate, csController.getAvailablePlacesForDate(selectedDate))) {
            placeComboBox.addItem(s);
        }
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void minageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minageTextFieldActionPerformed

    private void ticketTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketTextFieldActionPerformed

    private void placeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_placeComboBoxItemStateChanged
        if (placeComboBox.getSelectedIndex()==0) {
            return;
        }
        jLabel9.setText("Name:");
        jLabel10.setText("Email:");
        jLabel14.setText("Phone number:");
        jLabel15.setText("Address:");
        jLabel12.setText("Location:");
        jLabel11.setText("Maximum capacity:");
        Place selectedPlace = csController.getPlaceDetails(placeComboBox.getSelectedItem().toString());
        if (selectedPlace != null) {
            jLabel9.setText(jLabel9.getText()+" "+selectedPlace.getName());
            jLabel10.setText(jLabel10.getText()+" "+selectedPlace.getEmail());
            jLabel14.setText(jLabel14.getText()+" "+selectedPlace.getPhoneNumber());
            jLabel15.setText(jLabel15.getText()+" "+selectedPlace.getAddress().toString());
            jLabel12.setText(jLabel12.getText()+" "+selectedPlace.getLocation());
            jLabel11.setText(jLabel11.getText()+" "+selectedPlace.getMaxCapacity());
        }
    }//GEN-LAST:event_placeComboBoxItemStateChanged

    private void artistComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_artistComboBoxItemStateChanged
        if (placeComboBox.getSelectedIndex()==0) {
            return;
        }
    }//GEN-LAST:event_artistComboBoxItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jXDatePicker1.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please choose a date first!");
            return;
        }
        String artist = artistIDOf.get(String.valueOf(artistComboBox.getSelectedItem())); 
        String start = startTextField.getText();
        String place = String.valueOf(placeComboBox.getSelectedItem());
        String ticketPrice = ticketTextField.getText();
        String minAge = minageTextField.getText();
        if (artist == null || start.isEmpty() || place.isEmpty() || ticketPrice.isEmpty() || minAge.isEmpty()) {
           JOptionPane.showMessageDialog(null, "Please fill all the fields first!");
           return;
        }
        jPanel1.setVisible(true);
        jPanel1.setBounds(25, 305, 650, 260);
        Date selectedDate = new Date(jXDatePicker1.getDate().getDay(), jXDatePicker1.getDate().getMonth(), jXDatePicker1.getDate().getYear());
        DefaultTableModel model = new DefaultTableModel(); 
        jTable3.setModel(model);
        model.addColumn("Name"); 
        model.addColumn("Invite");
        TableColumn tc = jTable3.getColumnModel().getColumn(1);
        tc.setCellEditor(jTable3.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(jTable3.getDefaultRenderer(Boolean.class));
        Artist tmpArtist = null;
        for (String a : csController.getAvailableAdditionalArtists(selectedDate, artistIDOf.get(String.valueOf(artistComboBox.getSelectedItem())))) {
            tmpArtist = csController.getArtistDetails(a);
            if (tmpArtist != null)
                model.addRow(new Object[]{tmpArtist.getStageName(), false});
        }
        jTable3.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jTable3.getSelectedRow() > -1) {
                    jLabel20.setText("Agent:");
                    jLabel21.setText("Email:");
                    jLabel19.setText("Facebook:");
                    jLabel16.setText("Biography:");
                    Artist tmp = csController.getArtistDetails(artistIDOf.get(String.valueOf(jTable3.getValueAt(jTable3.getSelectedRow(),0))));
                    if (tmp != null) {
                        jLabel20.setText(jLabel20.getText()+" "+tmp.getAgent().getId());
                        jLabel21.setText(jLabel21.getText()+" "+tmp.getEmail());
                        jLabel19.setText(jLabel19.getText()+" "+tmp.getFacebook());
                        jLabel16.setText(jLabel16.getText()+" "+tmp.getBiography());
                    }
                }                
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void startTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String artist = artistIDOf.get(String.valueOf(artistComboBox.getSelectedItem())); 
        String agent = WindowManager.getTmpAgent().getId();
        Timestamp showDate = new Timestamp(jXDatePicker1.getDate().getTime());
        String start = startTextField.getText();
        String place = String.valueOf(placeComboBox.getSelectedItem());
        String ticketPrice = ticketTextField.getText();
        String minAge = minageTextField.getText();
        int showID = csController.newShow(artist, agent, showDate, start, Integer.valueOf(place), ticketPrice, minAge);
        int counter = 0;
        int anotherCounter = 0;
        for (int i = 0; i < jTable3.getRowCount(); i++) {
            if ((boolean)jTable3.getValueAt(i, 1)) {
                counter++;
                if (csController.newArtistInvitations(showID, artistIDOf.get((String)jTable3.getValueAt(i, 0)))) {
                    anotherCounter++;
                }
            }
        }
        if (showID > -1 && counter == anotherCounter) {
            JOptionPane.showMessageDialog(null,
                "Show was created successfully!",
                "Setup complete",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> artistComboBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTextField minageTextField;
    private javax.swing.JComboBox<String> placeComboBox;
    private javax.swing.JTextField startTextField;
    private javax.swing.JTextField ticketTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
