/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import businessLogic.CreateAgentControl;
import businessLogic.DBManager;
import businessLogic.HandsInTheAir;
import java.sql.ResultSet;

/**
 *
 * @author Yair Etzion
 */
public class HappyBirthday extends javax.swing.JPanel {

    /**
     * Creates new form CreateAgent
     */
    public HappyBirthday() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wallPaper = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(780, 580));
        setLayout(null);

        wallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container4.png"))); // NOI18N
        add(wallPaper);
        wallPaper.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel wallPaper;
    // End of variables declaration//GEN-END:variables
    private CreateAgentControl createAgentCon = new CreateAgentControl();
}
