/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import businessLogic.ReportProduceControl;
import businessLogic.ViewArtistsControl;
import businessLogic.WindowManager;
import static com.itextpdf.text.pdf.PdfFileSpecification.url;
import java.awt.Desktop;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author Shai Gutman
 */
public class ViewArtists extends javax.swing.JPanel {

    ReportProduceControl rpController = new ReportProduceControl();
    
    public ViewArtists() {
        if (WindowManager.getTmpUser()==null)
            return;
        initComponents();
        ResultSet rs = con.getArtists();
        if (rs!=null){
            try {
                while (rs.next())
                    jComboBox1.addItem(rs.getString(2));

            } catch (SQLException ex) {
                Logger.getLogger(ViewAgents.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new JList<String>(new DefaultListModel<String>());
        jComboBox1 = new javax.swing.JComboBox<>();
        titleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jButton2.setText("Click Here !");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(130, 100, 260, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Artists you fan of :");
        add(jLabel3);
        jLabel3.setBounds(510, 70, 190, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("FaceBook :");
        add(jLabel5);
        jLabel5.setBounds(30, 110, 90, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Biography :");
        add(jLabel11);
        jLabel11.setBounds(30, 160, 110, 15);
        add(jTextField4);
        jTextField4.setBounds(130, 100, 260, 30);
        jTextField4.setEditable(false);
        jTextField4.setVisible(false);
        add(jTextField9);
        jTextField9.setBounds(130, 160, 350, 150);
        jTextField9.setEditable(false);

        jButton1.setText("Become Fan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(590, 350, 190, 40);

        jLabel2.setText("* You can be a fan of 10 artists");
        add(jLabel2);
        jLabel2.setBounds(600, 400, 170, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Stage Name :");
        add(jLabel6);
        jLabel6.setBounds(30, 70, 90, 15);

        jScrollPane1.setViewportView(jList1);
        jList1.setEnabled(false);
        setList();

        add(jScrollPane1);
        jScrollPane1.setBounds(640, 70, 170, 200);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(130, 60, 260, 30);

        titleLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("View Artists");
        add(titleLabel);
        titleLabel.setBounds(0, 10, 850, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/container3.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if (con.becomeFan(artistSelected,artistSelectedName))
                setList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        ResultSet rs = con.getArtists();
        int count = jComboBox1.getSelectedIndex()+1;
        int counter = 1;
        try {
            while (rs.next()){
                if (counter == count){
                    artistSelected = rs.getString(1);
                    artistSelectedName = rs.getString(2);
                    jTextField4.setText(rs.getString(5));
                    jTextField9.setText(rs.getString(3));
                    break;
                }
                else counter++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewAgents.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            try {
                Desktop.getDesktop().browse(new URL(jTextField4.getText()).toURI());
            } catch (Exception e) {
                e.printStackTrace();
            }
            
    }//GEN-LAST:event_jButton2ActionPerformed
        
    public void setList(){
        ((DefaultListModel)jList1.getModel()).removeAllElements();
        
        for (String s : con.getFans())
             ((DefaultListModel)jList1.getModel()).addElement(s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    private ViewArtistsControl con = new ViewArtistsControl();
    private String artistSelected = null;
    private String artistSelectedName = null;
    
}
