/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package businessLogic;

import boundary.MainLogin;
import java.awt.Color;

/**
 *
 * @author Shai Gutman
 */
public abstract class DebugManager extends javax.swing.JFrame {
    private static int objects = 0;
    /**
     * Creates new form debugManager
     */
    public DebugManager() {
        initComponents();
        HandsInTheAir.setDebug(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        objectsCounterLabel = new javax.swing.JLabel();
        counterLabel = new javax.swing.JLabel();
        userBtn = new javax.swing.JButton();
        agentBtn = new javax.swing.JButton();
        placeBtn = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        databaseLabel = new javax.swing.JLabel();
        quickLog = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Debug window");
        setAlwaysOnTop(true);
        setFocusTraversalPolicyProvider(true);
        setPreferredSize(new java.awt.Dimension(305, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        objectsCounterLabel.setText("New objects:");
        getContentPane().add(objectsCounterLabel);
        objectsCounterLabel.setBounds(10, 180, 90, 14);

        counterLabel.setText(String.valueOf(objects));
        counterLabel.setForeground(Color.RED);
        getContentPane().add(counterLabel);
        counterLabel.setBounds(90, 180, 150, 16);

        userBtn.setText("User");
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        getContentPane().add(userBtn);
        userBtn.setBounds(150, 130, 70, 20);

        agentBtn.setText("Agent");
        agentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(agentBtn);
        agentBtn.setBounds(220, 130, 70, 20);

        placeBtn.setText("Place");
        placeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(placeBtn);
        placeBtn.setBounds(80, 130, 70, 20);

        adminBtn.setText("Admin");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adminBtn);
        adminBtn.setBounds(10, 130, 70, 20);
        getContentPane().add(statusLabel);
        statusLabel.setBounds(115, 160, 150, 16);

        databaseLabel.setText("Database status:");
        getContentPane().add(databaseLabel);
        databaseLabel.setBounds(10, 160, 100, 14);

        quickLog.setText("Quick login:");
        getContentPane().add(quickLog);
        quickLog.setBounds(10, 110, 80, 14);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/debugContainer.png"))); // NOI18N
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 300, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        if (WindowManager.getLoginFrame() == null)
            return;
        if (WindowManager.getMainFrame() != null)
            WindowManager.closeMain();
        WindowManager.getLoginFrame().extLogin("Admin", "Admin");
        WindowManager.getLoginFrame().openMain();
    }//GEN-LAST:event_adminBtnActionPerformed

    private void placeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBtnActionPerformed
        if (WindowManager.getLoginFrame() == null)
            return;
        if (WindowManager.getMainFrame() != null)
            WindowManager.closeMain();
        WindowManager.getLoginFrame().extLogin("Place", "Place");
        WindowManager.getLoginFrame().openMain();
    }//GEN-LAST:event_placeBtnActionPerformed

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        if (WindowManager.getLoginFrame() == null)
            return;
        if (WindowManager.getMainFrame() != null)
            WindowManager.closeMain();
        WindowManager.getLoginFrame().extLogin("efi@gmail.com", "123");
        WindowManager.getLoginFrame().openMain();
    }//GEN-LAST:event_userBtnActionPerformed

    private void agentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentBtnActionPerformed
        if (WindowManager.getLoginFrame() == null)
            return;
        if (WindowManager.getMainFrame() != null)
            WindowManager.closeMain();
        WindowManager.getLoginFrame().extLogin("kadisha@gmail.com", "123");
        WindowManager.getLoginFrame().openMain();
    }//GEN-LAST:event_agentBtnActionPerformed

    public static void setDatabaseStatus(Boolean flag) {
        if (flag) {
            statusLabel.setText("connected");
            statusLabel.setForeground(Color.green);
            return;
        }
        statusLabel.setText("not connected");
        statusLabel.setForeground(Color.red);
    }
    
    public static void objectsPlusPlus() {
        objects++;
        counterLabel.setText(String.valueOf(objects));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton adminBtn;
    private static javax.swing.JButton agentBtn;
    private static javax.swing.JLabel counterLabel;
    private static javax.swing.JLabel databaseLabel;
    private static javax.swing.JLabel objectsCounterLabel;
    private static javax.swing.JButton placeBtn;
    private static javax.swing.JLabel quickLog;
    private static javax.swing.JLabel statusLabel;
    private static javax.swing.JButton userBtn;
    private static javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
